# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TemplateQgisPlugin
                                 A QGIS plugin
 This is template of QGIS Plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-18
        copyright            : (C) 2024 by HogeHoge
        email                : HugaHuga@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
os.chdir(os.path.dirname(__file__))

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TemplateQgisPlugin class from file TemplateQgisPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .template_qgis_plugin import TemplateQgisPlugin
    return TemplateQgisPlugin(iface)
